Introduce event handlers & clean up Entity
Developer-DAO/Lens-Graph-Subgraph pull request #30
Opened 2022-11-09 15:51 UTC by andyrobert3

This PR aims to fix the following issues:
- https://github.com/Developer-DAO/Lens-Graph-Subgraph/issues/17
- https://github.com/Developer-DAO/Lens-Graph-Subgraph/issues/16

Fixes typo with `onwedBy` in `ProfileCreated` handler

## Changes
- Updated entities for `Post`, `Comment` & `Mirror` to be simpler, without the bloatware we had before
Since the voyager map view is not available, I am basing the structure of the entities with the events emitted by Lens
We can always add the necessary fields back for the schema, when we find an event handler that provides those values

- Normalised the schema a bit, by adding `posts`, `comments` & `mirrors` into the `Profile` schema
We should be combining the `Post`, `Comment` & `Mirror` to inherit from a superclass type `Publication` since they are just subclasses of it, according to the lens docs

https://docs.lens.xyz/docs/comment
https://docs.lens.xyz/docs/publication
https://docs.lens.xyz/docs/mirror

Will continue writing PR for these issues:
- https://github.com/Developer-DAO/Lens-Graph-Subgraph/issues/19
- https://github.com/Developer-DAO/Lens-Graph-Subgraph/issues/18

2022-11-10 10:04 UTC, Nazeeh21 requested changes
Added comments for the `schema.graphql` file. All other things are perfect. Thanks mate! you've done an amazing job!

2022-11-10 10:04 UTC, naz3eh commented on schema.graphql
> -  isFollowingMe: Boolean
@andyrobert3 Any specific reason why removed some of the fields from the entity? I had a look at the lens URL you put as a comment and I guess you updated the `schema` by looking at the fields from the `ProfileCreated` event from the lens. 
But I think, at this point in time keeping next week's demo in mind, I think would be better if we don't do major breaking changes. 
I'd suggest just adding the additional fields to the entities (as this would prevent the existing queries from getting broken) and if we feel the requirement to remove some of the fields that are unnecessary then we'll create an issue and would proceed from there. 
Happy to hear your thoughts on this. :)

2022-11-10 10:04 UTC, naz3eh commented on schema.graphql
> -  hasCollectedByMe: Boolean!
Similar to the case with these fields as well.

2022-11-10 10:04 UTC, naz3eh commented on schema.graphql
> -  hasCollectedByMe: Boolean!
similar the scenario with these fields as well

2022-11-10 10:04 UTC, Nazeeh21 commented on src/lens-hub.ts
>  }
Amazing job mate!! @andyrobert3

2022-11-10 15:53 UTC, andyrobert3 commented on schema.graphql
> -  isFollowingMe: Boolean
ok sure, i'll just add them back with a comment saying that we should refactor the additional fields

2022-11-11 19:20 UTC, Nazeeh21 approved these changes
LGTM! Merging

2022-11-11 19:21 UTC, merged